{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-service
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}-service
  template:
    metadata:
      labels:
        app: {{ $name }}-service
    spec:
      containers:
      - name: {{ $name }}-service
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        command: ["sh", "-c", "go run main.go"]
        workingDir: /app
        volumeMounts:
        - mountPath: /app
          name: {{ $name }}-code
        ports:
        - containerPort: {{ $svc.port }}
      volumes:
      - name: {{ $name }}-code
        hostPath:
          path: /home/professor/microservices/{{ $name }}-service
          type: Directory
---
{{- end }}
