{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
spec:
  type: NodePort
  selector:
    app: {{ $name }}-service
  ports:
    - protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      nodePort: {{ add 30080 (sub $svc.port 8080) }}
---
{{- end }}
