registry: localhost:32000

order-service:
  replicaCount: 1
  image:
    repository: localhost:32000/order-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30081
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUPercent: 60
    scaleDownStabilizationSeconds: 60
    scaleDownPeriodSeconds: 30

product-service:
  replicaCount: 1
  image:
    repository: localhost:32000/product-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30082
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUPercent: 60
    scaleDownStabilizationSeconds: 60
    scaleDownPeriodSeconds: 30

inventory-service:
  replicaCount: 1
  image:
    repository: localhost:32000/inventory-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30083
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  hpa:
    enabled: false
  keda:
    minReplicas: 1
    maxReplicas: 10
    consumerGroup: inventory-service
    topic: orders
    lagThreshold: "5"
    bootstrapServers: kafka.default.svc.cluster.local:9092


