{{- range $name, $cfg := .Values }}
{{- if and (kindIs "map" $cfg) (hasKey $cfg "image") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  {{- if and
        (not (and (hasKey $cfg "hpa") $cfg.hpa.enabled))
        (not (hasKey $cfg "keda"))
  }}
  replicas: {{ $cfg.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $cfg.image.repository }}:{{ $cfg.image.tag }}"
          imagePullPolicy: {{ $cfg.image.pullPolicy }}
          ports:
            - containerPort: 8080
          {{- if $cfg.env }}
          env:
            {{- range $key, $val := $cfg.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml $cfg.resources | nindent 12 }}
{{- end }}
{{- end }}

