{{- range $name, $cfg := .Values }}
{{- if kindIs "map" $cfg }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ $cfg.service.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $cfg.service.port }}
      targetPort: 8080
      nodePort: {{ $cfg.service.nodePort }}
{{- end }}
{{- end }}


