{{- range $name, $cfg := .Values }}
{{- if and (kindIs "map" $cfg) (hasKey $cfg "image") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: {{ $cfg.service.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $cfg.service.port }}
      targetPort: 8080
      {{- if eq $cfg.service.type "NodePort" }}
      nodePort: {{ $cfg.service.nodePort }}
      {{- end }}
{{- end }}
{{- end }}

